# basic options
title: Vakantie Juni 2018
author: Kees
description: Blog van de kampeervakantie van juni 2018
URL: "https://prudento-nl.github.io/2018-06-kamperen-frankrijk"
images: "https://prudento-nl.github.io/2018-06-kamperen-frankrijk/images"

# Build settings
markdown: kramdown
theme: minima
