# basic options
title: Vakantie Juni 2018 config
author: Teksten geschreven door Kees
description: Website gemaakt door Kees
URL: "https://prudento-nl.github.io/2018-06-kamperen-frankrijk/"

# Build settings
markdown: kramdown
theme: jekyll-theme-minimal
